In [1]:
import tensorflow as tf
from tensorflow import keras

from keras.models import Sequential, Model
from keras.layers import Dense, Conv2D, GlobalAveragePooling2D, Flatten, Dropout, BatchNormalization
from keras.preprocessing import image
from keras.preprocessing import image_dataset_from_directory
from keras.applications import EfficientNetB0
from keras.applications.efficientnet import preprocess_input


In [2]:
#Loading data

train = image_dataset_from_directory(
    directory="../data/kaggle/train",
    label_mode='categorical',
    color_mode='rgb',
    image_size=(224,224),
    batch_size=32

)

test = image_dataset_from_directory(
    directory="../data/kaggle/test",
    label_mode='categorical',
    color_mode='rgb',
    image_size=(224,224),
    batch_size=32,
    shuffle=False
)

Found 31140 files belonging to 6 classes.
Found 3928 files belonging to 6 classes.


In [3]:
# Preprocessing images
def preprocess(image, label):
    image = preprocess_input(image)

    return image, label

train_data = train.map(preprocess)
test_data = test.map(preprocess)


In [4]:
train_data = train_data.prefetch(buffer_size = tf.data.AUTOTUNE)
test_data = test_data.prefetch(buffer_size = tf.data.AUTOTUNE)

In [5]:
augment_data = Sequential([
    
    keras.layers.RandomFlip('horizontal'),
    keras.layers.RandomFlip('vertical'),
    keras.layers.RandomZoom(0.2),
    keras.layers.RandomRotation(0.2),
    keras.layers.RandomContrast(0.2),
    keras.layers.RandomTranslation(0.2, 0.2),
    keras.layers.RandomShear(x_factor=0.05, y_factor=0.05, fill_mode='constant')

])

In [6]:
base_model = EfficientNetB0(weights='imagenet',include_top=False, input_shape=(224,224,3))

In [7]:
print(len(base_model.layers))

238


In [8]:
base_model.trainable = True

for layer in base_model.layers[:-25]:
    layer.trainable = False

In [9]:
inputs = keras.Input(shape=(224,224,3))
x = augment_data(inputs)


x = base_model(x, training=False)

x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)

outputs = Dense(len(train.class_names),
                activation='softmax',
                kernel_regularizer=tf.keras.regularizers.l2(0.001))(x)

model = keras.Model(inputs, outputs)

In [10]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ sequential (Sequential)         │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ efficientnetb0 (Functional)     │ (None, 7, 7, 1280)     │     4,049,571 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       163,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 6)              │           774 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,214,825 (16.08 MB)

 Trainable params: 1,627,750 (6.21 MB)

 Non-trainable params: 2,587,075 (9.87 MB)

In [11]:
from keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

In [12]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

y_true = np.concatenate([y for x, y in train_data], axis=0)
y_labels = np.argmax(y_true, axis=1)

classes = np.unique(y_labels)

weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y_labels
)

class_weights = dict(zip(classes, weights))

In [13]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
              loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.05), 
              metrics=["accuracy"])

In [14]:
history = model.fit(train_data, epochs=60, validation_data=test_data, callbacks=early_stop, class_weight=class_weights)

Epoch 1/60
974/974 ━━━━━━━━━━━━━━━━━━━━ 1681s 2s/step - accuracy: 0.5435 - loss: 1.3143 - val_accuracy: 0.6909 - val_loss: 1.0047
Epoch 2/60
974/974 ━━━━━━━━━━━━━━━━━━━━ 1549s 2s/step - accuracy: 0.6357 - loss: 1.0591 - val_accuracy: 0.7100 - val_loss: 0.9165
Epoch 3/60
974/974 ━━━━━━━━━━━━━━━━━━━━ 1514s 2s/step - accuracy: 0.6718 - loss: 0.9815 - val_accuracy: 0.7304 - val_loss: 0.8703
Epoch 4/60
974/974 ━━━━━━━━━━━━━━━━━━━━ 1447s 1s/step - accuracy: 0.6917 - loss: 0.9359 - val_accuracy: 0.7253 - val_loss: 0.8645
Epoch 5/60
974/974 ━━━━━━━━━━━━━━━━━━━━ 1453s 1s/step - accuracy: 0.7086 - loss: 0.9039 - val_accuracy: 0.7245 - val_loss: 0.9164
Epoch 6/60
974/974 ━━━━━━━━━━━━━━━━━━━━ 1487s 2s/step - accuracy: 0.7244 - loss: 0.8613 - val_accuracy: 0.7566 - val_loss: 0.8267
Epoch 7/60
974/974 ━━━━━━━━━━━━━━━━━━━━ 1622s 2s/step - accuracy: 0.7371 - loss: 0.8383 - val_accuracy: 0.7503 - val_loss: 0.8453
Epoch 8/60
974/974 ━━━━━━━━━━━━━━━━━━━━ 1482s 2s/step - accuracy: 0.7472 - loss: 0.8088 - 

In [15]:
class_names = train.class_names

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report

y_true = []
y_pred = []

for images, labels in test:
    pred = model.predict(images)

    y_true.extend(np.argmax(labels.numpy(), axis = 1))
    y_pred.extend(np.argmax(pred, axis = 1))

y_true = np.array(y_true)
y_pred = np.array(y_pred)


1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 961ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 854ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 955ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 893ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 868ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 915ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 880ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 869ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 897ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 876ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 890ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 870ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 844ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 916ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 874ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 860ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 886ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 866ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 903ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 857ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 900ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 946ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 953ms/

In [16]:
print(confusion_matrix(y_true, y_pred))

[[ 280    5    8   20    2    7]
 [  12 1079   37   51  167   15]
 [   4    4  440   44   14    4]
 [  24   19  109  554   20   24]
 [   3   90   27   24  694   11]
 [   7    0   22   13    6   88]]


In [17]:



print(classification_report(y_true, y_pred, target_names=class_names))



              precision    recall  f1-score   support

        Akne       0.85      0.87      0.86       322
      Benign       0.90      0.79      0.84      1361
      Ekzama       0.68      0.86      0.76       510
Enfeksiyonel       0.78      0.74      0.76       750
      Malign       0.77      0.82      0.79       849
     Pigment       0.59      0.65      0.62       136

    accuracy                           0.80      3928
   macro avg       0.76      0.79      0.77      3928
weighted avg       0.81      0.80      0.80      3928



In [20]:
model.save('../model/efficientnet_model.keras')

In [19]:
import json

with open('../model/class_names.json','w') as f:
    json.dump(class_names,f)